name: CI Taskflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-and-test:
    name: Lint & Test Application
    runs-on: [self-hosted, lab]

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Configuration Node.js via Action Composite
        uses: ./.github/actions/setup-node-project
        with:
          node-version: "20"

      - name: 1. Linting
        run: npm run lint

      - name: 2. Tests unitaires
        run: npm run test

      - name: 3. Build de l'application
        run: npm run build
